function showQuote(){
var quotes= [
"No man need despair of gaining converts to the most extravagant hypothesis who has art enough to represent it in favorable colors.<br> - David Hume",
"Say what you will about the sweet miracle of unquestioning faith, I consider a capacity for it terrifying and absolutely vile.<br> - Kurt Vonnegut Jr.",
"Aphorisms are something like jewels; rarity increases their value, and they are enjoyable only in small doses.<br> - Hermann Hesse",
"Who would ever think that so much went on in the soul of a young girl?<br> - Anne Frank",
"All religions, arts and sciences are branches of the same tree. All these aspirations are directed toward ennobling man's life, lifting it from the sphere of mere physical existence and leading the individual towards freedom.<br> - Albert Einstein",
"Life is either a daring adventure or nothing at all.<br> - Helen Keller",
"Character cannot be developed in ease and quiet. Only through experience of trial and suffering can the soul be strengthened, vision cleared, ambition inspired, and success achieved.<br> - Helen Keller",
"I admit that I ain't no angel, I admit that I ain't no saint. I'm selfish and I'm cruel and I'm blind. If I exorcise my devils, well my angels may leave too. When they leave they're so hard to find...<br> - Tom Waits",
"The man who does not read good books has no advantage over the man who can't read them.<br> - Mark Twain",
"It seems that different people have an idea of what I am, and what I should be. And then there's me.<br> - Ani DiFranco",
"Outside of a dog, a book is man's best friend. Inside of a dog it's too dark to read.<br> - Groucho Marx",
"I hate quotations.<br> - Ralph Waldo Emerson",
"Nowadays most people die of a sort of creeping common sense, and discover when it is too late that the only things one never regrets are one's mistakes.<br> - Oscar Wilde",
"Life presents us with alternatives which are equally plausable without being instinctive.<br> - Guildenstern",
"Nothing is true. Everything is permissable.<br> - Hassan-i Sabbah",
"There are risks and costs to a program of action, but they are far less than the long-range risks and costs of comfortable inaction<br> - John F. Kennedy",
"The most important thing is this: to be able at any moment to sacrifice what we are for what we could become.<br> - Charles Du Bos",
"No one who, like me, conjures up the most evil of those half-tamed demons that inhabit the human breast, and seeks to wrestle with them, can expect to come through the struggle unscathed.<br> - Sigmund Freud",
"Open your eyes, look within. Are you satisfied with the life you're living?<br> - Bob Marley",
"I think of myself as an intelligent, sensitive human being with the soul of a clown which always forces me to blow it at the most important moments.<br> - Jim Morrison",
"Strength is Happiness. Strength is itself victory. In weakness and cowardice there is no happiness. When you wage a struggle, you might win or you might lose. But regardless of the short-term outcome, the very fact of your continuing to struggle is proof of your victory as a human being.<br> - Daisaku Ikeda",
"The greater danger for most of us lies not in setting our aim too high and falling short; but in setting our aim too low, and achieving our mark.<br> - Michelangelo",
"We cross our bridges when we come to them and burn them behind us, with nothing to show for our progress except a memory of the smell of smoke, and a presumption that once our eyes watered.<br> - Guildenstern",
"You should not see the desert simply as some faraway place of little rain. There are many forms of thirst.<br> - William Langewiesche",
"Your reality, sir, is lies and balderdash and I'm delighted to say that I have no grasp of it whatsoever.<br> - Baron Munchausen",
"By working faithfully eight hours a day you may eventually get to be boss and work twelve hours a day.<br> - Robert Frost",
"There are only two ways to live your life. One is as though nothing is a miracle. The other is as though everything is a miracle.<br> - Albert Einstein",
"Well, I've wrestled with reality for 35 years, Doctor, and I'm happy to state I finally won out over it. - Elwood P. Dowd",
"The only way to deal with an unfree world is to become so absolutely free that your very existence is an act of rebellion.<br> -Albert Camus",
"Before enlightenment; chop wood, carry water. After enlightenment; chop wood, carry water.<br> - Zen Proverb",
"My manner of thinking, so you say, cannot be approved. Do you suppose I care? A poor fool indeed is he who adopts a manner of thinking for others!<br> -Marquis De Sade",
"The eagle never lost so much time as when he submitted to learn of the crow.<br> - William Blake",
"Be patient. You'll know when it's time for you to wake up and move ahead<br> - Ram Dass",
"If we could read the secret history of our enemies, we would find in each person's life sorrow and suffering enough to disarm all hostility.<br> Henry Wadsworth Longfellow",
"I am a jelly doughnut.<br> - John F. Kennedy",
"Consistency is the hobgoblin of little minds,<br> - Emerson",
"When I let go of what I am, I become what I might be. - Lao Tzu",
"I am free, no matter what rules surround me. If I find them tolerable, I tolerate them; if I find them too obnoxious, I break them. I am free because I know that I alone am morally responsible for everything I do.<br> - Robert A. Heinlein",
"Imagination is the real and eternal world of which this vegetable universe is but a faint shadow.<br> - William Blake",
"Playing small does not serve the world. There is nothing enlightened about shrinking so that other people will not feel insecure around you. We are all meant to shine, as children do.<br> - Marianne Deborah Williamson",
"Wherefore do ye toil; is it not that ye may live and be happy? And if ye toil only that ye may toil more, when shall happiness find you? Ye toil to live, but is not life made of beauty and song? ... Toil without song is like a weary journey without an end. Were not death more pleasing?<br> - H.P. Lovecraft",
"Whatever course you decide upon, there is always someone to tell you that you are wrong. There are always difficulties arising which tempt you to believe that your critics are right. To map out a course of action and follow it to an end requires courage.<br> - Ralph Waldo Emerson",
"We write to taste life twice, in the moment and in retrospection.<br> - Anais Nin",
"Wile E. Coyote, Supergenius. I like the way it rolls out.<br> - Wile E. Coyote (Supergenius)",
"I'm attracted to the extreme light and the extreme dark. I'm interested in the human condition and what makes people tick. I'm interested in the things people try to hide.<br> - Johnny Depp",
"If god is watching us, the least we can do is be entertaining.<br> - Dave Dunseath",
"You can go wrong by being too skeptical as readily as by being too trusting.<br> - Lazarus Long",
"Imagination is more important than knowledge. For knowledge is limited to all we now know and understand, while imagination embraces the entire world, and all there ever will be to know and understand.<br> - Albert Einstein",
"Never be certain of anything. It's a sign of weakness.<br> - Doctor Who",
"If you are great, El Topo is a great picture. If you are limited, El Topo is limited.<br> - Alejandro Jodorowsky",
"It may be better to be a live jackal than a dead lion, but it is better still to be a live lion.<br> - Robert Heinlein",
"Truth is not what you want it to be; it is what it is, and you must bend to its power or live a lie.<br> - Miyamoto Musashi",
"Every normal man must be tempted, at times, to spit upon his hands, hoist the black flag, and begin slitting throats.<br> - H. L. Mencken",
"Man cannot remake himself without suffering, for he is both the marble and sculptor.<br>  - Alexis Carrel",
"There is nothing noble in being superior to your fellow man; true nobility is being superior to your former self.<br> - Ernest Hemingway",
"When you are dead, you do not know you are dead. It's only painful & difficult for others. The same applies when you are stupid.<br> - Philippe Geluck",
"You get a strange feeling when you're about to leave a place. Like you'll not only miss the people you love but you'll miss the person you are now at this time and this place, because you'll never be this way ever again.<br> - Azar Nafisi"
];
        var whichQuote=Math.floor(Math.random()*(quotes.length));
        document.getElementById('quoteOfTheDay').innerHTML = (quotes[whichQuote]);

}
showQuote();